name: image_magick_q8
description: Dart bindings for ImageMagick C library which is used to edit images.
version: 1.0.0
homepage: https://github.com/Haidar0096/image_magick_q8
repository: https://github.com/Haidar0096/image_magick_q8
documentation: https://github.com/Haidar0096/image_magick_q8

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.11.0"

dependencies:
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.1

dev_dependencies:
  ffigen: ^7.2.0
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
        dartPluginClass: ImageMagickFFIPlugin
      linux:
        ffiPlugin: true
        dartPluginClass: ImageMagickFFIPlugin
      windows:
        ffiPlugin: true
        dartPluginClass: ImageMagickFFIPlugin